server:
  port: 8070

#jdbc
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gmall?useSSL=false&serverTimezone=UTC
    username: root
    password: admin@123
  dubbo:
    #dubbo服务的扫描路径
    base-package: com.atguigu.gmall
    #dubbo中的服务名称
    application: user-service
    protocol:
      #dubbo通讯协议名称
      name: dubbo
    registry:
      #zookeeper注册中心的地址
      address: 192.168.174.145:2181
      #zookeeper通讯协议名称
      protocol: zookeeper
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

#日志级别
logging:
  level:
    root: debug

