#·þÎñ¶Ë¿ÚºÅ
server:
  port: 8080

#jdbc
spring:
  datasource:
    url: jdbc://mysql://192.168.100.20:3306
    username: test
    password: 12346
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true


